# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
title                    : "Meryem Seyda Ozcan"
title_separator          : "-"
name                     : &name "Meryem Seyda Ozcan"
description              : &description "About Me
I am Meryem Seyda Ozcan, a doctoral candidate in Developmental Psychology at Koç University, conducting my research in the Independent Evaluation Lab. I am also a visiting scholar at the CoDeS Lab at Virginia Tech. My research focuses on the intersection of cognitive development and technology, particularly how media and technology can enhance children's learning outcomes and cognitive skills. Throughout my academic journey, I have led interdisciplinary projects that explore how media use, contextual factors, and personalized technologies influence children’s cognitive and socioemotional development. I utilize a range of quantitative methods, including advanced statistical techniques, systematic reviews, and meta-analyses, to gain insights that can improve educational practices.

My work is driven by a commitment to optimizing media and technology for positive developmental outcomes, providing actionable insights for parents, educators, and policymakers. I aim to bridge the gap between research and practice, creating educational solutions that empower children and foster their growth."
url                      : https://meryemseydaozcan.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/HomePage" # the subpath of your site, e.g. "/blog"
repository               : "meryemseydaozcan.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Meryem Seyda Ozcan"
  pronouns         : # she/her"  
  bio              : "Ph.D. Candidate at Koç University & Visiting Scholar at Virginia Tech"
  location         : "Blacksburg, VA"
  employer         : ""
  uri              : # URL
  email            : "seyda24@vt.edu" 

  # Academic websites
  arxiv            : 
  googlescholar    : "https://scholar.google.com/citations?user=psTkdgcAAAAJ&hl=tr&oi=ao"
  impactstory      : 
  orcid            : "http://orcid.org/my-orcid?orcid=0000-0002-3209-8888"
  semantic         : 
  pubmed           : 
  researchgate     : # https://www.researchgate.net/profile/Meryem-Oezcan

  # Repositories and software development
  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : 
  kaggle           : 
  stackoverflow    : 

  # Social media
  bluesky          : "bsky.app" # Replace this with you Bluesky username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # seyda_zayim
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username

# Publication Category - The following the list of publication categories and their headings
publication_category:
    title: 'Journal Articles'    
1.	Oksuz, I., Özcan, M. Ş., Dost-Gözkan, A., & Kisbu, Y. (in press). Health risk behaviors of adolescents in Europe: A latent profile analysis of HBSC data from 43 countries. Journal of Adolescent Health.
2.	Özcan, M. Ş., Goksun, T., & Kisbu Sakarya, Y. (2024). The impact of learning to code on higher-order executive functions: A systematic review of the literature. Journal of Research on Technology in Education. https://doi.org/10.1080/15391523.2024.2381231
3.	Kisbu, Y., Özcan, M. Ş., Kuşcul, G. H., Bozok, M., Kaya, M., & Fişek, G. (2023). Fathering styles in a traditional culture and its association with marital relationship: A latent profile analysis with a nationally representative sample. Family Process, 00, 1–23. https://doi.org/10.1111/famp.12948
4.	Akcaoglu, M., Özcan, M. Ş., & Hodges, C. B. (2023). Exploring the relationship among motivational constructs and preservice teachers’ use of computational thinking in classrooms. Computers in the Schools, 1-17. https://doi.org/10.1080/07380569.2023.2172987
5.	Akcaoglu, M., Ozcan, M. Ş., & Dogan, S. (2023). What keeps teachers engaged during professional development? The role of interest development. Education Sciences, 13, 188. https://doi.org/10.3390/educsci13020188
6.	Özcan, M. Ş., Çetinkaya, E., Goksun, T., & Kisbu Sakarya, Y. (2021). Does learning to code influence cognitive skills of elementary school children? Findings from a randomized experiment. British Journal of Educational Psychology, 91, 1434-1455. https://doi.org/10.1111/bjep.12429
    title: 'Journal Articles Under Review'
1.	Özcan, M. Ş., & Kisbu, Y. (under review). Exposure to interactive media, but at low levels, is associated with better executive functioning in children: A meta-analysis. Media Psychology.
2.	Özcan, M. Ş., & Akcaoglu, M. (under review). Development and validation of the multidimensional interest development survey (MIS): An interest survey measuring phases and components. Instructional Science.
3.	Sabuncuoglu, A., Özcan, M. Ş., Kisbu, Y., & Sezgin, M. (under review). Developing an open-source middle school programming environment and its curriculum for an affordable education. British Journal of Educational Technology.
4.	Rajadhyaksha, U., Aycan, Z., Rantanen, J., Feldt, T., Cinli, D., Özcan, M. Ş., & Baskurt, A. B. (under review). Work-family interface during COVID-19: Gender and gender role ideology perspectives. Journal of Family and Economic Issues.
  title: 'Journal Articles in Preparation'
1.	Özcan, M. Ş., Lee, Y., & Choi, K. (in preparation). The associations between problematic media use and executive functions in middle childhood: A cross-lagged panel model.
2.	Beers, C., Yu, S., Özcan, M. Ş., Smith, C. L., & Choi, K. (in preparation). Understanding media guilt among mothers of young children.
3.	Özcan, M. Ş., & Choi, K. (in preparation). The role of digital media on young children’s executive functions: Testing potential moderating and mediating effects.
  conferences:
    title: 'Conference Papers'
1.	Özcan, M. Ş., & Kisbu, Y. (2024, March 21-23). Exposure to interactive media, but at low levels, is associated with better executive functioning in children: A meta-analysis [Poster presentation]. Cognitive Developmental Society Biennial Conference 2024, Pasadena, CA.
2.	Oksuz, I., Özcan, M. Ş., Sunmaz, N., & Kisbu, Y. (2023, September 6-8). Health risk behaviors among European adolescents: A latent profile analysis [Conference presentation abstract]. II. International Adolescence and Youth Research Congress, Kapadokya, Turkiye. https://www.egad2023.org/downloads/kongre_ozet_kitabi.pdf
3.	Turunç, G., & Özcan, M. Ş. (2023, September 6-8). Bullying and adolescent well-being: Insights from Bronfenbrenner’s bioecological systems theory [Paper presentation abstract]. II. International Adolescence and Youth Research Congress, Kapadokya, Turkiye. https://www.egad2023.org/downloads/kongre_ozet_kitabi.pdf
4.	Özcan, M. Ş., Turunç, G., Çetinkaya, E., & Kisbu, Y. (2022, September 8-9). Cognitive functions and academic skills in children living under conflict: Investigation of mediation mechanisms using UNICEF MICS Palestine data. [Poster presentation] Third Development Symposium in Turkiye, Istanbul, Turkiye.
5.	Özcan, M. Ş., Çetinkaya, E., Goksun, T., & Kisbu Sakarya, Y. (2021, April 7-9). Does learning to code improve cognitive skills of elementary school children? [Poster presentation]. The Society for Research in Child Development Biennial Meeting (SRCD), virtual.
6.	Zayim, M. Ş., & Kisbu-Sakarya, Y. (2019, March 21-23). Fathering styles in Turkey: A latent profile analysis based on a representative sample. [Poster presentation]. The Society for Research in Child Development Biennial Meeting (SRCD), Baltimore, MD.
# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false     # change to true to hide the RSS feed in the footer
  path                   : # blank (default) uses feed.xml


# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :


# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 :  # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles


# Analytics
analytics:
  provider               :  "false" # false (default), "google", "google-universal", "google-analytics-4", "custom"
  google:
    tracking_id          :


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# These settings control the types of collections used by the template
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/


# These settings control how pages and collections are included in the site
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Etc/UTC # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
